CREATE TABLE PROGRAMADORES (
    PROGRA_CODIGO SERIAL NOT NULL,
    PROGRA_NOMBRE VARCHAR (25),
    PROGRA_APELLIDO VARCHAR (25),
    PROGRA_EDAD INT, 
    PROGRA_CORREO VARCHAR (50),
    PROGRA_DIRECCION VARCHAR (50),
    PROGRA_TELEFONO INTEGER,
    PROGRA_DEPENDENCIA VARCHAR (25),
    PROGRA_GENERO VARCHAR (20),
    PROGRA_SITUACION INTEGER DEFAULT 1,
    PRIMARY KEY (PROGRA_CODIGO)
);

CREATE TABLE APLICACION (
    APLI_CODIGO SERIAL NOT NULL,
    APLI_NOMBRE VARCHAR (25),
    APLI_DEPENDENCIA VARCHAR (25),
    APLI_DESCRIPCION VARCHAR (50),
    PRIMARY KEY (APLI_CODIGO)
);

CREATE TABLE TAREA(
    TAREA_CODIGO SERIAL NOT NULL,
    TAREA_NOMBRE INT,
    TAREA_APLICACION INT,
    TAREA_DESCRIPCION VARCHAR(100),
    TAREA_SITUACION INT DEFAULT 1,
    PRIMARY KEY (TAREA_CODIGO),
    FOREIGN KEY (TAREA_NOMBRE) REFERENCES PROGRAMADORES(PROGRA_CODIGO),
    FOREIGN KEY (TAREA_APLICACION) REFERENCES APLICACION(APLI_CODIGO)
);