CREATE TABLE PROGRAMADORES (
    PROGRA_ID SERIAL NOT NULL,
    PROGRA_NOMBRE VARCHAR (25),
    PROGRA_APELLIDO VARCHAR (25),
    PROGRA_EDAD INTEGER, 
    PROGRA_CORREO VARCHAR (50),
    PROGRA_DIRECCION VARCHAR (50),
    PROGRA_TELEFONO INTEGER,
    PROGRA_DEPENDENCIA VARCHAR (25),
    PROGRA_GENERO VARCHAR (20),
    PROGRA_SITUACION INTEGER DEFAULT 1,
    PRIMARY KEY (PROGRA_ID)
);

CREATE TABLE APLICACIONES (
    APP_ID SERIAL NOT NULL,
    APP_NOMBRE VARCHAR (25),
    APP_CANTIDAD INTEGER,
    APP_REGISTRO DATETIME YEAR TO MINUTE,
    APP_TIPO VARCHAR (25),
    APP_ENTREGA DATETIME YEAR TO MINUTE,
    APP_DEPENDENCIA VARCHAR (25),
    APP_DESCRIPCION VARCHAR (100),
    APP_SITUACION INTEGER DEFAULT 1,
    PRIMARY KEY (APP_ID)
);

CREATE TABLE TAREA(
    TAREA_ID SERIAL NOT NULL,
    TAREA_PROGRAMADOR INTEGER,
    TAREA_APLICACION INTEGER,
    TAREA_DESCRIPCION VARCHAR(100),
    TAREA_SITUACION INT DEFAULT 1,
    PRIMARY KEY (TAREA_ID),
    FOREIGN KEY (TAREA_PROGRAMADOR) REFERENCES PROGRAMADORES (PROGRA_ID),
    FOREIGN KEY (TAREA_APLICACION) REFERENCES APLICACIONES (APP_ID)
);